[2024-09-18T20:37:54.989+0000] {processor.py:186} INFO - Started process (PID=761) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:37:54.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:37:54.996+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:37:54.995+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:37:55.018+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:37:55.005+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 6, in <module>
    "start_date": datetime(2024, 1, 1),
                  ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'
[2024-09-18T20:37:55.028+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:37:55.069+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.101 seconds
[2024-09-18T20:38:05.158+0000] {processor.py:186} INFO - Started process (PID=762) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:05.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:38:05.164+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:05.163+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:05.175+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:05.168+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 6, in <module>
    "start_date": datetime(2024, 1, 1),
                  ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'
[2024-09-18T20:38:05.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:05.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.074 seconds
[2024-09-18T20:38:08.210+0000] {processor.py:186} INFO - Started process (PID=769) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:08.213+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:38:08.218+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:08.217+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:08.235+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:08.223+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 8, in <module>
    "start_date": datetime(2024, 1, 1),
                  ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'
[2024-09-18T20:38:08.245+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:08.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.110 seconds
[2024-09-18T20:38:09.320+0000] {processor.py:186} INFO - Started process (PID=770) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:09.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:38:09.327+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:09.326+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:09.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:09.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.069 seconds
[2024-09-18T20:38:23.793+0000] {processor.py:186} INFO - Started process (PID=774) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:23.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:38:23.802+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:23.802+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:23.812+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:23.809+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:38:23.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:23.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.090 seconds
[2024-09-18T20:38:33.886+0000] {processor.py:186} INFO - Started process (PID=775) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:33.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:38:33.903+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:33.903+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:33.927+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:33.918+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:38:33.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:34.021+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.152 seconds
[2024-09-18T20:38:37.043+0000] {processor.py:186} INFO - Started process (PID=782) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:37.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:38:37.053+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:37.053+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:37.073+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:37.069+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:38:37.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:37.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.101 seconds
[2024-09-18T20:38:39.124+0000] {processor.py:186} INFO - Started process (PID=783) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:39.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:38:39.132+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:39.131+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:39.140+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:39.137+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:38:39.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:39.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.066 seconds
[2024-09-18T20:38:49.511+0000] {processor.py:186} INFO - Started process (PID=787) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:49.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:38:49.517+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:49.517+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:49.522+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:49.520+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:38:49.523+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:49.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.053 seconds
[2024-09-18T20:38:55.566+0000] {processor.py:186} INFO - Started process (PID=788) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:55.567+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:38:55.571+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:55.570+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:55.576+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:55.574+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:38:55.576+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:55.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.055 seconds
[2024-09-18T20:38:57.657+0000] {processor.py:186} INFO - Started process (PID=789) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:57.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:38:57.662+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:57.662+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:57.667+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:57.665+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:38:57.668+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:57.727+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.081 seconds
[2024-09-18T20:38:59.688+0000] {processor.py:186} INFO - Started process (PID=790) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:59.688+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:38:59.692+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:59.692+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:59.697+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:38:59.696+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:38:59.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:38:59.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.054 seconds
[2024-09-18T20:39:30.486+0000] {processor.py:186} INFO - Started process (PID=800) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:39:30.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:39:30.492+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:39:30.491+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:39:30.497+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:39:30.495+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:39:30.498+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:39:30.528+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.052 seconds
[2024-09-18T20:40:00.992+0000] {processor.py:186} INFO - Started process (PID=810) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:40:00.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:40:00.999+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:40:00.998+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:40:01.004+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:40:01.002+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:40:01.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:40:01.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.052 seconds
[2024-09-18T20:40:31.430+0000] {processor.py:186} INFO - Started process (PID=820) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:40:31.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:40:31.436+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:40:31.436+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:40:31.441+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:40:31.439+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:40:31.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:40:31.472+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.051 seconds
[2024-09-18T20:41:01.899+0000] {processor.py:186} INFO - Started process (PID=830) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:01.901+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:41:01.907+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:01.907+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:01.915+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:01.912+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:41:01.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:01.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.079 seconds
[2024-09-18T20:41:14.992+0000] {processor.py:186} INFO - Started process (PID=836) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:14.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:41:14.997+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:14.996+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:15.002+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:15.000+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:41:15.003+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:15.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.049 seconds
[2024-09-18T20:41:20.423+0000] {processor.py:186} INFO - Started process (PID=840) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:20.424+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:41:20.429+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:20.429+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:20.435+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:20.433+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:41:20.436+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:20.465+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.054 seconds
[2024-09-18T20:41:25.477+0000] {processor.py:186} INFO - Started process (PID=841) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:25.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:41:25.487+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:25.486+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:25.494+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:25.491+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:41:25.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:25.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.068 seconds
[2024-09-18T20:41:28.586+0000] {processor.py:186} INFO - Started process (PID=842) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:28.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:41:28.591+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:28.591+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:28.605+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:28.602+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:41:28.607+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:28.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.095 seconds
[2024-09-18T20:41:32.645+0000] {processor.py:186} INFO - Started process (PID=843) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:32.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:41:32.652+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:32.651+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:32.659+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:32.657+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:41:32.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:32.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.067 seconds
[2024-09-18T20:41:34.703+0000] {processor.py:186} INFO - Started process (PID=844) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:34.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:41:34.717+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:34.716+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:34.735+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:34.731+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:41:34.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:34.822+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.144 seconds
[2024-09-18T20:41:36.913+0000] {processor.py:186} INFO - Started process (PID=851) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:36.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:41:36.936+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:36.935+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:36.946+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:36.942+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:41:36.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:36.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.118 seconds
[2024-09-18T20:41:51.286+0000] {processor.py:186} INFO - Started process (PID=855) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:51.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:41:51.293+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:51.292+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:51.299+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:51.297+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:41:51.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:51.336+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.060 seconds
[2024-09-18T20:41:55.329+0000] {processor.py:186} INFO - Started process (PID=856) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:55.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:41:55.335+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:55.334+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:55.341+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:55.339+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:41:55.342+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:55.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.057 seconds
[2024-09-18T20:41:57.350+0000] {processor.py:186} INFO - Started process (PID=857) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:57.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:41:57.357+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:57.356+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:57.365+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:57.362+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:41:57.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:57.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.073 seconds
[2024-09-18T20:41:59.449+0000] {processor.py:186} INFO - Started process (PID=858) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:59.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:41:59.455+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:59.454+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:59.461+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:41:59.459+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:41:59.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:41:59.494+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.056 seconds
[2024-09-18T20:42:26.519+0000] {processor.py:186} INFO - Started process (PID=868) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:26.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:42:26.524+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:42:26.524+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:26.530+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:42:26.529+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:42:26.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:26.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.061 seconds
[2024-09-18T20:42:32.575+0000] {processor.py:186} INFO - Started process (PID=869) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:32.576+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:42:32.581+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:42:32.580+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:32.587+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:42:32.584+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:42:32.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:32.620+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.056 seconds
[2024-09-18T20:42:36.615+0000] {processor.py:186} INFO - Started process (PID=870) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:36.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:42:36.620+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:42:36.619+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:36.625+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:42:36.623+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:42:36.626+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:36.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.051 seconds
[2024-09-18T20:42:42.732+0000] {processor.py:186} INFO - Started process (PID=877) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:42.733+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:42:42.738+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:42:42.737+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:42.743+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:42:42.741+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:42:42.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:42.771+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.051 seconds
[2024-09-18T20:42:58.461+0000] {processor.py:186} INFO - Started process (PID=881) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:58.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:42:58.478+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:42:58.477+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:58.494+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:42:58.491+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:42:58.499+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:42:58.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.158 seconds
[2024-09-18T20:43:05.664+0000] {processor.py:186} INFO - Started process (PID=882) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:43:05.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:43:05.671+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:43:05.670+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:43:05.676+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:43:05.675+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:43:05.678+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:43:05.714+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.065 seconds
[2024-09-18T20:43:25.065+0000] {processor.py:186} INFO - Started process (PID=892) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:43:25.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:43:25.070+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:43:25.070+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:43:25.076+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:43:25.074+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 8
    "start_date": datetime(2024, , 1),
                                 ^
SyntaxError: invalid syntax
[2024-09-18T20:43:25.077+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:43:25.108+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.054 seconds
[2024-09-18T20:43:27.086+0000] {processor.py:186} INFO - Started process (PID=893) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:43:27.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:43:27.092+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:43:27.092+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:43:27.097+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:43:27.096+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:43:27.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:43:27.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.056 seconds
[2024-09-18T20:43:57.749+0000] {processor.py:186} INFO - Started process (PID=903) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:43:57.752+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:43:57.756+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:43:57.756+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:43:57.762+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:43:57.760+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 17
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 13
[2024-09-18T20:43:57.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:43:57.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.052 seconds
[2024-09-18T20:44:14.062+0000] {processor.py:186} INFO - Started process (PID=909) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:14.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:44:14.068+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:14.068+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:14.097+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:14.094+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7
    from scripts
                ^
SyntaxError: invalid syntax
[2024-09-18T20:44:14.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:14.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.184 seconds
[2024-09-18T20:44:18.148+0000] {processor.py:186} INFO - Started process (PID=910) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:18.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:44:18.153+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:18.153+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:18.158+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:18.156+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7
    from scripts.
                 ^
SyntaxError: invalid syntax
[2024-09-18T20:44:18.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:18.207+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.071 seconds
[2024-09-18T20:44:19.265+0000] {processor.py:186} INFO - Started process (PID=911) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:19.266+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:44:19.270+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:19.270+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:19.276+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:19.274+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7
    from scripts.hello_world
                            ^
SyntaxError: invalid syntax
[2024-09-18T20:44:19.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:19.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.058 seconds
[2024-09-18T20:44:22.745+0000] {processor.py:186} INFO - Started process (PID=915) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:22.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:44:22.750+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:22.750+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:22.755+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:22.753+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7
    from scripts.hello_world import 
                                    ^
SyntaxError: invalid syntax
[2024-09-18T20:44:22.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:22.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.048 seconds
[2024-09-18T20:44:24.781+0000] {processor.py:186} INFO - Started process (PID=916) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:24.784+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:44:24.788+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:24.788+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:24.799+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:24.796+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 19
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 15
[2024-09-18T20:44:24.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:24.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.086 seconds
[2024-09-18T20:44:26.860+0000] {processor.py:186} INFO - Started process (PID=917) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:26.862+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:44:26.868+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:26.867+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:26.875+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:26.872+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7
    from scripts.hello_world import
                                   ^
SyntaxError: invalid syntax
[2024-09-18T20:44:26.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:26.922+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.076 seconds
[2024-09-18T20:44:57.276+0000] {processor.py:186} INFO - Started process (PID=927) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:57.278+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:44:57.283+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:57.282+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:57.290+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:44:57.287+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7
    from scripts.hello_world import
                                   ^
SyntaxError: invalid syntax
[2024-09-18T20:44:57.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:44:57.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.069 seconds
[2024-09-18T20:45:11.392+0000] {processor.py:186} INFO - Started process (PID=933) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:11.398+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:45:11.404+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:11.403+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:11.416+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:11.409+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7
    from scripts.script1 import
                               ^
SyntaxError: invalid syntax
[2024-09-18T20:45:11.417+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:11.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.095 seconds
[2024-09-18T20:45:17.541+0000] {processor.py:186} INFO - Started process (PID=934) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:17.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:45:17.547+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:17.546+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:17.554+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:17.552+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 19
    max_active_runs=1) as dag:
                              ^
IndentationError: expected an indented block after 'with' statement on line 15
[2024-09-18T20:45:17.555+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:17.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.062 seconds
[2024-09-18T20:45:32.983+0000] {processor.py:186} INFO - Started process (PID=938) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:32.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:45:33.001+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:33.001+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:33.043+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:33.032+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7, in <module>
    from scripts.script1 import hello_world
ModuleNotFoundError: No module named 'scripts.script1'
[2024-09-18T20:45:33.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:33.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.157 seconds
[2024-09-18T20:45:39.042+0000] {processor.py:186} INFO - Started process (PID=946) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:39.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:45:39.049+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:39.048+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:39.058+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:39.056+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7, in <module>
    from scripts.script1 import hello_world
ModuleNotFoundError: No module named 'scripts.script1'
[2024-09-18T20:45:39.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:39.104+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.075 seconds
[2024-09-18T20:45:48.125+0000] {processor.py:186} INFO - Started process (PID=947) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:48.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:45:48.133+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:48.132+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:48.143+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:48.140+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7, in <module>
    from scripts.script1 import hello_world
ModuleNotFoundError: No module named 'scripts.script1'
[2024-09-18T20:45:48.144+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:48.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.072 seconds
[2024-09-18T20:45:53.256+0000] {processor.py:186} INFO - Started process (PID=948) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:53.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:45:53.274+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:53.273+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:53.282+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:53.280+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7, in <module>
    from scripts.script1 import hello_world
ModuleNotFoundError: No module named 'scripts.script1'
[2024-09-18T20:45:53.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:53.325+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.083 seconds
[2024-09-18T20:45:56.674+0000] {processor.py:186} INFO - Started process (PID=952) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:56.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:45:56.684+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:56.682+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:56.694+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:56.691+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7, in <module>
    from scripts.script1 import hello_world
ModuleNotFoundError: No module named 'scripts.script1'
[2024-09-18T20:45:56.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:56.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.150 seconds
[2024-09-18T20:45:57.669+0000] {processor.py:186} INFO - Started process (PID=953) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:57.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:45:57.674+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:57.674+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:57.681+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:45:57.679+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7, in <module>
    from scripts.script1 import hello_world
ModuleNotFoundError: No module named 'scripts.script1'
[2024-09-18T20:45:57.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:45:57.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.052 seconds
[2024-09-18T20:46:01.708+0000] {processor.py:186} INFO - Started process (PID=954) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:46:01.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:46:01.714+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:46:01.713+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:46:01.722+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:46:01.720+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7, in <module>
    from scripts.script1 import hello_world
ModuleNotFoundError: No module named 'scripts.script1'
[2024-09-18T20:46:01.723+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:46:01.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.066 seconds
[2024-09-18T20:46:04.867+0000] {processor.py:186} INFO - Started process (PID=955) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:46:04.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:46:04.879+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:46:04.878+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:46:04.897+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:46:04.895+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7, in <module>
    from scripts.script1 import hello_world
ModuleNotFoundError: No module named 'scripts.script1'
[2024-09-18T20:46:04.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:46:05.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.225 seconds
[2024-09-18T20:46:10.928+0000] {processor.py:186} INFO - Started process (PID=961) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:46:10.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:46:10.959+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:46:10.958+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:46:10.990+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:46:10.987+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7, in <module>
    from scripts.script1 import hello_world
ModuleNotFoundError: No module named 'scripts.script1'
[2024-09-18T20:46:11.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:46:11.047+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.134 seconds
[2024-09-18T20:46:41.376+0000] {processor.py:186} INFO - Started process (PID=970) to work on /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:46:41.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/jw_ocl_guide.py for tasks to queue
[2024-09-18T20:46:41.386+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:46:41.385+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:46:41.394+0000] {logging_mixin.py:190} INFO - [2024-09-18T20:46:41.391+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/jw_ocl_guide.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jw_ocl_guide.py", line 7, in <module>
    from scripts.script1 import hello_world
ModuleNotFoundError: No module named 'scripts.script1'
[2024-09-18T20:46:41.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/jw_ocl_guide.py
[2024-09-18T20:46:41.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/jw_ocl_guide.py took 0.082 seconds
